version: "3.8"

volumes:
  ew_node:
    external: true
  ew_postgresql:
    external: true

services:
  # Ergo blockchain node
  node:
    image: ergoplatform/ergo:v4.0.13
    command: --mainnet -c /etc/ergo.conf
    volumes:
      - ew_node:/home/ergo/.ergo
      - ./node/ergo.conf:/etc/ergo.conf:ro
    ports:
      - "127.0.0.1:9053:9053"
      - "9030:9030"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # Postgresql database
  db:
    build:
      context: ./explorer-backend/db
    environment:
      POSTGRES_DB: ergo
      POSTGRES_USER: ergo
    env_file:
      # Defines POSTGRES_PASSWORD
      - ./explorer-backend/db/db.secret
    volumes:
      - ew_postgresql:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
 
  # Ergo explorer backend chain grabber 
  grabber:
    build:
      context: ./explorer-backend/8.1.0
      dockerfile: chain-grabber.Dockerfile
    volumes:
      - ./explorer-backend/conf/explorer-backend.conf:/explorer-backend.conf:ro
    command: /explorer-backend.conf
    links:
      - "node"
      - "db"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # Syncer - triggers db updates when grabber add new block
  syncer:
    build:
      context: ./syncer
    environment:
      DB_HOST: db
      DB_NAME: ergo
      DB_USER: ergo
    env_file:
      # Defines POSTGRES_PASSWORD
      - ./explorer-backend/db/db.secret
    links:
      - "db"
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "3"

  # API server
  api:
    build:
      context: ./api
    env_file:
      # Defines POSTGRES_PASSWORD
      - ./explorer-backend/db/db.secret
    links:
      - "db"
    ports:
      - "127.0.0.1:8000:80"
    restart: unless-stopped
    volumes:
      - ./api/src/main:/app
    logging:
      options:
        max-size: "10m"
        max-file: "3"