debug = false

# Write blocks to db in batches of 
# batch_size = 10

[database]
host = "localhost"
port = 5432
name = "db"
user = "user"
pw = "hello"

[node]
url = "http://127.0.0.1:9053"

